version: '3.8'

services:
  db:
    image: postgres:16
    container_name: sql_playground_db
    restart: always
    environment:
      POSTGRES_DB: playground
      POSTGRES_USER: playground_user
      POSTGRES_PASSWORD: playground_pass
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
